## Пример 1.2.1
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [1]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


## Пример 1.2.2
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


## Пример 1.2.3
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.

In [4]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.002009254551578077 0.99764707278472 0.48633754732293105


## Пример 1.2.4
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.

In [5]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Пример 1.2.5
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [6]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.inf)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## Пример 1.2.6
Отсортировать массив

In [7]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


## 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy

arr = numpy.array(
    [[0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0]])
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [12]:
arr = numpy.arange(0, 25).reshape(5, 5)
for i in range(len(arr)):
    arr[i] = numpy.arange(0, 5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [13]:
arr = numpy.random.random((3, 3, 3))
print(arr)

[[[0.9119817  0.3009009  0.00391653]
  [0.31584222 0.92079682 0.07000327]
  [0.62490707 0.85435932 0.71050407]]

 [[0.52056218 0.63274808 0.67600585]
  [0.46973566 0.99787815 0.5032654 ]
  [0.64877824 0.93709783 0.37175687]]

 [[0.71472306 0.70626297 0.60185664]
  [0.59595544 0.25671304 0.67546246]
  [0.6198267  0.43544915 0.7879987 ]]]


## 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [17]:
arr = numpy.zeros((6, 6))
for i in range(1, len(arr) - 1):
    for j in range(1, len(arr[i]) - 1):
        arr[i, j] = 1
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [42]:
arr = numpy.random.randint(0, 20, 10)
print(arr)
arr = numpy.sort(arr)[::-1]
print(arr)

[ 5  3 17  9  0  9 10 11  0 15]
[17 15 11 10  9  9  5  3  0  0]


## 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [45]:
arr = numpy.random.randint(0, 20, (3, 5))
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 5)
15
2


## Пример 2.2.1
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [8]:
import pandas as pd

lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])
s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


## Пример 2.2.2
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [9]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s3[3:])

1
5
d    4
e    5
dtype: int32


## Пример 2.2.3
Создайте новый фрейм данных.

In [10]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

## Пример 2.2.4
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [11]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

## Пример 2.2.5
Пронализировать характеристики фрейма данных.

In [12]:
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## Пример 2.2.6
Выберите индивидуальные данные или срезы фрейма данных.

In [13]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

## Пример 2.2.7
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [14]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## 2.3.1 Задание
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [48]:
import pandas

a = pandas.Series([1, 2, 3, 4, 5])
b = pandas.Series([4, 2, 5, 13, 5])
sum = 0
for i in range(len(a)):
    sum += (a[i] - b[i]) ** 2
print(sum ** (1 / 2))

9.695359714832659


## 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [55]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dframe = pandas.read_csv(url)
dframe.head(10)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   
5                             Anderson, Mr Harry    1st  47.00    male   
6               Andrews, Miss Kornelia Theodosia    1st  63.00  female   
7                         Andrews, Mr Thomas, jr    1st  39.00    male   
8   Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.00  female   
9                         Artagaveytia, Mr Ramon    1st  71.00    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0  
5         1        0  
6         1        1  
7         0        0  
8         1        1  
9         0        0

## 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [61]:
dframe.head(2)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [62]:
dframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [63]:
dframe.shape

(1313, 6)

In [64]:
dframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [65]:
dframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [66]:
dframe[dframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## Пример 3.2.1
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [18]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

## Пример 3.2.2
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное
отклонение 1.

In [20]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized
print("Среднее: ", round(standardized.mean()))
print("Стандартное отклонение: ", round(standardized.std()))

Среднее:  0
Стандартное отклонение:  1


## Пример 3.2.3
Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.

In [24]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A': [14.00, 90.20, 90.95, 96.27, 91.21],
                      'B':[103.02, 107.26, 110.35, 114.23, 114.68],
                      'C': ["big", "small", "big", "small", "small"]})

dfTest[['A','B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

## 3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [13]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

scaler = MinMaxScaler()
dframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
dframe[['sepal_length_cm']] = scaler.fit_transform(dframe[['sepal_length_cm']])
dframe[['sepal_width_cm']] = preprocessing.normalize(dframe[['sepal_width_cm']])
dframe.head(5)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222             1.0              1.4             0.2  setosa
1         0.166667             1.0              1.4             0.2  setosa
2         0.111111             1.0              1.3             0.2  setosa
3         0.083333             1.0              1.5             0.2  setosa
4         0.194444             1.0              1.4             0.2  setosa