## 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [1]:
import numpy

arr = numpy.array(
    [[0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0],
     [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0]])
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.

In [12]:
arr = numpy.arange(0, 25).reshape(5, 5)
for i in range(len(arr)):
    arr[i] = numpy.arange(0, 5)
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


## 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [13]:
arr = numpy.random.random((3, 3, 3))
print(arr)

[[[0.9119817  0.3009009  0.00391653]
  [0.31584222 0.92079682 0.07000327]
  [0.62490707 0.85435932 0.71050407]]

 [[0.52056218 0.63274808 0.67600585]
  [0.46973566 0.99787815 0.5032654 ]
  [0.64877824 0.93709783 0.37175687]]

 [[0.71472306 0.70626297 0.60185664]
  [0.59595544 0.25671304 0.67546246]
  [0.6198267  0.43544915 0.7879987 ]]]


## 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [17]:
arr = numpy.zeros((6, 6))
for i in range(1, len(arr) - 1):
    for j in range(1, len(arr[i]) - 1):
        arr[i, j] = 1
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [42]:
arr = numpy.random.randint(0, 20, 10)
print(arr)
arr = numpy.sort(arr)[::-1]
print(arr)

[ 5  3 17  9  0  9 10 11  0 15]
[17 15 11 10  9  9  5  3  0  0]


## 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [45]:
arr = numpy.random.randint(0, 20, (3, 5))
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 5)
15
2


## 2.3.1 Задание
Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.

In [48]:
import pandas

a = pandas.Series([1, 2, 3, 4, 5])
b = pandas.Series([4, 2, 5, 13, 5])
sum = 0
for i in range(len(a)):
    sum += (a[i] - b[i]) ** 2
print(sum ** (1 / 2))

9.695359714832659


## 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [55]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dframe = pandas.read_csv(url)
dframe.head(10)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   
5                             Anderson, Mr Harry    1st  47.00    male   
6               Andrews, Miss Kornelia Theodosia    1st  63.00  female   
7                         Andrews, Mr Thomas, jr    1st  39.00    male   
8   Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.00  female   
9                         Artagaveytia, Mr Ramon    1st  71.00    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0  
5         1        0  
6         1        1  
7         0        0  
8         1        1  
9         0        0

## 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.

In [61]:
dframe.head(2)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [62]:
dframe.tail(3)

Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [63]:
dframe.shape

(1313, 6)

In [64]:
dframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [65]:
dframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [66]:
dframe[dframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

## 3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [80]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dframe = pandas.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')
dframe[['sepal_length_cm']] = scaler.fit_transform(dframe[['sepal_length_cm']])
dframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222             3.5              1.4             0.2   
1           0.166667             3.0              1.4             0.2   
2           0.111111             3.2              1.3             0.2   
3           0.083333             3.1              1.5             0.2   
4           0.194444             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667             3.0              5.2             2.3   
146         0.555556             2.5              5.0             1.9   
147         0.611111             3.0              5.2             2.0   
148         0.527778             3.4              5.4             2.3   
149         0.444444             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]